name: Lint, Package & Deploy Script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Ensure Dependencies (ShellCheck and SSH tools)
      run: |
         sudo apt-get update
         sudo apt-get install -y shellcheck openssh-client

    - name: Lint script
      run: shellcheck setup-ssh-deployment.sh

    - name: Test script syntax
      run: bash -n setup-ssh-deployment.sh

    - name: Make script executable
      run: chmod +x setup-ssh-deployment.sh

    - name: Package script
      run: tar -czf healthcheck.tar.gz setup-ssh-deployment.sh

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

    - name: Copy script to remote VM
      run: scp healthcheck.tar.gz ${{ secrets.VM_USER }}@${{ secrets.VM_HOST 
}}:~/healthcheck-deploy/

    - name: Run script on remote VM
      run: |
        ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          mkdir -p ~/healthcheck-deploy
          cd ~/healthcheck-deploy
          tar -xzf healthcheck.tar.gz
          chmod +x setup-ssh-deployment.sh
          ./setup-ssh-deployment.sh
        EOF

